openapi: 3.0.2
info:
  title: API Spec
  version: '1.0'
  description: >
    `API v1 Spec`
servers:
  - url: https://localhost:3000/api
    description: local server

# ================================================================================
components:
  schemas:
    $ref: 'schemas.yaml'

# ================================================================================
paths:
  # --------------------------------------------------
  /members:
    get:
      description:
        メンバー取得
      parameters:
        - name: limit
          in: query
          description: 取得件数
          schema:
            type: integer
            default: 100
        - name: offset
          in: query
          description: オフセット
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                description:
                  レスポンス
                type: object
                required:
                  - response
                properties:
                  response:
                    $ref: 'index.yaml#/components/schemas/Response'
                  members:
                    type: array
                    items:
                      $ref: 'index.yaml#/components/schemas/Member'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: 'index.yaml#/components/schemas/Error'
    post:
      description:
        メンバー作成
      parameters:
        - name: code
          in: query
          description: ログインID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                description:
                  レスポンス
                type: object
                required:
                  - response
                properties:
                  response:
                    $ref: 'index.yaml#/components/schemas/Response'
                  member:
                    $ref: 'index.yaml#/components/schemas/Member'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: 'index.yaml#/components/schemas/Error'
  # --------------------------------------------------
  /members/{code}:
    get:
      description:
        メンバー詳細
      parameters:
        - name: code
          in: path
          description: ログインID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                description:
                  レスポンス
                type: object
                required:
                  - response
                  - member
                properties:
                  response:
                    $ref: 'index.yaml#/components/schemas/Response'
                  member:
                    $ref: 'index.yaml#/components/schemas/Member'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: 'index.yaml#/components/schemas/Error'
    delete:
      description:
        メンバー削除
      parameters:
        - name: code
          in: path
          description: ログインID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                description:
                  レスポンス
                type: object
                required:
                  - response
                properties:
                  response:
                    $ref: 'index.yaml#/components/schemas/Response'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: 'index.yaml#/components/schemas/Error'